START TRANSACTION;

CREATE TABLE "DelegationEmailNotificationLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "DelegationEndDate" timestamp without time zone NOT NULL,
    "NotifiedOnUtc" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_DelegationEmailNotificationLog" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DelegationEmailNotificationLog_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DelegationEmailNotificationLog_UserId" ON "DelegationEmailNotificationLog" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230523120702_DelegationEmailNotificationLog', '5.0.10');

COMMIT;

