START TRANSACTION;

ALTER TABLE "CcsService" ADD "GlobalLevelOrganisationAccess" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "ExternalServiceRoleMapping" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CcsServiceId" integer NOT NULL,
    "OrganisationEligibleRoleId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ExternalServiceRoleMapping" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExternalServiceRoleMapping_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExternalServiceRoleMapping_OrganisationEligibleRole_Organis~" FOREIGN KEY ("OrganisationEligibleRoleId") REFERENCES "OrganisationEligibleRole" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ExternalServiceRoleMapping_CcsServiceId" ON "ExternalServiceRoleMapping" ("CcsServiceId");

CREATE INDEX "IX_ExternalServiceRoleMapping_OrganisationEligibleRoleId" ON "ExternalServiceRoleMapping" ("OrganisationEligibleRoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211103081721_ExternalServiceRoleMapping', '5.0.10');

COMMIT;

