START TRANSACTION;

ALTER TABLE "User" ADD "CcsServiceId" integer NULL;

CREATE TABLE "UserIdentityProvider" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationEligibleIdentityProviderId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserIdentityProvider" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserIdentityProvider_OrganisationEligibleIdentityProvider_O~" FOREIGN KEY ("OrganisationEligibleIdentityProviderId") REFERENCES "OrganisationEligibleIdentityProvider" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserIdentityProvider_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_User_CcsServiceId" ON "User" ("CcsServiceId");

CREATE INDEX "IX_UserIdentityProvider_OrganisationEligibleIdentityProviderId" ON "UserIdentityProvider" ("OrganisationEligibleIdentityProviderId");

CREATE INDEX "IX_UserIdentityProvider_UserId" ON "UserIdentityProvider" ("UserId");

ALTER TABLE "User" ADD CONSTRAINT "FK_User_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211108030518_UserMultipleIdpAndServiceId', '5.0.10');

COMMIT;

