version: 2
updates:
  # Maintain dependencies for NuGet
  - package-ecosystem: "nuget"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 25