  language: node_js
  node_js:
  - 12.16.1
  addons:
    chrome: stable
  cache:
    directories:
    - "./node_modules"
  install:
  - npm install
  before_script:
  - npm install -g @angular/cli
  script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  before_deploy:
    - npm run build -- --prod --base-href /
    - cd dist
    - cp index.html 404.html
  deploy:
    - provider: cloudfoundry
      username:
        secure: Cnvxi4EQvMeuksD/oadKMQ7Ccl/S0zJQknpfnSm1J1EcOn2nvBPiLDtkY0CoedKc+bNfl0KiGHZ/NoLfUvY20Qf9quas54ZuLhrF3Vo/jC9crmAVXnvP17hDeVCVlA8kSZuZrnkhUFbY60BpGxdFiAunPhlVg0Y0uVeEwX7GEO+S3DRfWVVD4OKm5Ph+ynu6VjS9UwmQP2VoK70Ozf/M/UvWV9liWASnRbOCh6nfC2u80qco0y+b2tmPVlmaVSzFrw9aOAnwPiwFepeae0M+5Qb2rQFdSc//i6KIc+8x3k5FyBronttmXp1eXzdJmN4oaWmpO0Nn+yfKkE0UOw1Hq1cazBjVYxx5t8UnykDJBSIWvboJcxoSNf9BRSGWLooYndulIumetTvwuOl46CbfiyMzR3CVLSb5zlY6fc8fo+YS+2ymUdX3wgpmDVXf/SPX1oZMpqm1QWpd+yZ5KubVmvT1h+LD1UlAXRW0YltOtFCqUghGbnP6+R7t17ZLkEOoFBjgZ05/qcwOC6s9n6mvgfrD2kMrbn6kAN+6WveRU4PJFBhhWh7pNKRHN0fosuQZFxXTM2bM4r/mJJOO6ejpmmMNnp++HJ4hHBnQiEaCL3qqU7X4lpYOCSAa7jbci8SYgl4FvElhG8xSkHc9woHlW7OYynqSGg/c6ywz2aiC8q4=
      password:
        secure: Gw9JJcKiNy7rbUqVdpE1NkluZALSm9te5CD3daJhYkqSx4QWbGspqUZkbla2sSPxI0D1QKVpuxkJiJ88ZNKX5SyqMBz181BrWvqTt7RrFNA9Ce1jViz7V/UW0orSAHd0L8iAhi3kccGwYoQMCK7vQ9fE4XYdJrNLw7TTFMvKn9ML+kT0WojNz+Zlu2A2H8LUVHla4DaX7NNEW+e+nwfNo8lR0+M8DCDmkRj0ZvRfpGYmlIEfvfUOlkrghVXO+C3r5hCu+2X1Kw/uHXK9uLNb65ti7fRLMc1cMEywqpDNklg3Kpm92/qrMNzEFy1K2bRrLLrP/mQwhbh5USOcKPBWx0E5bVIRUIybTjpYJxm0nvebi2oTal/htgNIM+4rBxb9QWLRqO8bJsHFnyfg1QrInVH2TTOO3tAK/vJIJd6spWiov6JZ/iJ6JyJvJ/tvli7sMQ7u9N0ARMeYQf7W9u+l+D3M24QVJzs3kPot7r5YbFAP+G4P6xS/5VLe9jcqrSMSIfVfPftD7DEhUauHCDsTnfVk4nNIauO/zDsgsZGdwN2v2uoIH6OyzehtGKjJ7DVgrcC1qKfsWP55Um4eSPn+5Ib/vVRHVWyjwbSETjEYhO+wikNq/u0w0ZDMY2SeUAdeqyGGoYLxzRNKaGgC5HL6ySYo2jfaf+h5bcO67r0KBdw=
      api:
        secure: ULSpfF9wpXsHf8bGZjkGznpVqB2zSuHbVdaKjudhYbLY3V1+0Rg/82ZV1m1E/BRK+QGtRQJwa0l1eoTqQqRZ0BDfPrlJwwXEaD+f/eNM54S/tv+n4qkORtxQ/Lwm38doNhQQU8inr09rqkcruEs+GAKM/mN9rrKZNVNHhB/soVhhRkFCjq5oaQ/kEcnIhP0JKDVrxdOfaKihORt2pLK+vQKBhpD5FTHFAZJfbarb02+eqCKV7a7YEeAklW8LirLNy80q/zPkq1TVHK6if27pF+TQ85sQeOhs+N1skGJw2a5wuLtZEAo1Wl06tPjYK9hi76IXi4llVInLy7QKNQjCeK4cjxsNrawnZf9idq5S/dQP7dZeZkorE/zJIp7XsjKUwE3FkgS0SYevE094O5tlfP5IPQEwzGeUPp1aUu2sYCbIouuy4dZwZSDJ4FwA9se05R6ebt8W5S3ZDtbyPVXLbK96E1VFQPuDBiBkyikCc+TJIvPF7gFK0bM4dKbQEcNcoTO+wWaDMHi0ZA4Rmy/vmmL3JNLa84Rj8OljwbxZjjJo3m2MiBMdUxQo3KAQlCDfJ1N7neSeelOW8VaHsl7fNuxy9W5Kgli0qsgSqfu1mwIL+nOaCpg7z25vDdgIWYyhogAXWAUUGf/Q1bmSQIi8RQl/9iu0BK8iS9j7kbR+Mkk=
      organization:
        secure: f+mY3rT2Ogk791ttZwAyzvwCn6rG1M+B8nrdXHkLn4TgpwCiW1hVID8hY/tCjGJZgz3bkAtkb58wzSVslhbOYCvWzZy3khnaRqpBO5xrYAqNb9uQpwisK7HRX29S7Q1VYhNSoed98aK2DM1EZIvtoOEo+HeMqZl5rA1NqeULUsPvr7PRuzieWFaahC6DaSsq0VeHU0q0ThxC+D1g4sxqy+9wlk2wFCGEMGETtt4nSHfWutwZlARrqdzVryR6EKH+aeX+MBhd26F/HBHcaBbpLHOI27aziQU4DYaAQC5j8/CezCiBowUJp/z4sMqp+WAOmcNZy0veGR1wSfrxWM7RkTLuj6j28UZwMb6tYZ4w5//Ozskbw/q144JdVTRm8pXLAhPVe7hroKOKv6w2gSudYPa+vskDO+j6Sw4XzG8nAg4m7gAlna0zpX9r4iGk993sk8tU3xxxvlvMVAeWbqR6WUfYfUpjqmcpRGyg1HJKTILfIaVHnlygTviU0UtmLpR5zsWq0CizUdiV5gctjm99skp0flk+UAVdOClVTKfZ7A/6y0GaAV7I9jjfLPjKJfMtJZYHiixQYaSDO/SpAoWY4NKPhx/wjwTqXqhzDfXHFMHDAUFOhE/g9CM768ToyFkSh45tQAaxY5UJQTLri7CZaQwyqxUknWojPDtmLYhczro=
      space: development
      manifest: ../manifest.yml
      skip-cleanup: true
      on:
        branch: travis
