dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
language: csharp
dotnet: 5.0.1
solution: ./api/CcsSso.sln
install:
  - dotnet restore ./api/CcsSso.sln
mono: none
script:
  - dotnet build --configuration Release ./api/CcsSso.sln
deploy:
  - provider: cloudfoundry
    username: $CF_USERNAME
    password: $CF_PASSWORD
    api: $CF_API
    organization: $CF_ORGANIZATION
    space: uat
    manifest: /home/travis/build/$GITHUB_USER/conclave-sso/manifest.yml
    skip-cleanup: true
    repo: Crown-Commercial-Service/conclave-ssso
    edge: true
    on:
      branch: uat
