dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest/beta
sudo: required
language: csharp
dotnet: 5.0.1
solution: ./api/CcsSso.sln
install:
  - dotnet restore ./api/CcsSso.sln
mono: none
script:
  - dotnet build --configuration Release ./api/CcsSso.sln
  - pwd
deploy:
  - provider: cloudfoundry
    username: $username
    password: $password
    api: $api
    organization: $organisation
    space: uat
    manifest: manifest.yml
    skip-cleanup: true
    edge: true
    on:
      branch: uat
