---
applications:
- name: sand-api-security
  instances: 1
  memory: 512M
  path: api/CcsSso.Security.Api/bin/Release/net6.0
  buildpack: https://github.com/cloudfoundry/dotnet-core-buildpack.git
  routes:
    - route: sand-api-security.london.cloudapps.digital
  services:
    - sand-security-pg-service
    - sand-vault 
    - sand-security-redis-service
  env:
    CACHE_NUGET_PACKAGES: false