CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AuditLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Event" text NULL,
    "UserId" integer NOT NULL,
    "Application" text NULL,
    "ReferenceData" text NULL,
    "IpAddress" text NULL,
    "Device" text NULL,
    "EventTimeUtc" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_AuditLog" PRIMARY KEY ("Id")
);

CREATE TABLE "BulkUploadDetail" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" text NULL,
    "FileKey" text NULL,
    "FileKeyId" text NULL,
    "DocUploadId" text NULL,
    "BulkUploadStatus" integer NOT NULL,
    "ValidationErrorDetails" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_BulkUploadDetail" PRIMARY KEY ("Id")
);

CREATE TABLE "CcsAccessRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CcsAccessRoleNameKey" text NULL,
    "CcsAccessRoleName" text NULL,
    "CcsAccessRoleDescription" text NULL,
    "MfaEnabled" boolean NOT NULL,
    "OrgTypeEligibility" integer NOT NULL,
    "SubscriptionTypeEligibility" integer NOT NULL,
    "TradeEligibility" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_CcsAccessRole" PRIMARY KEY ("Id")
);

CREATE TABLE "CcsService" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServiceName" text NULL,
    "Description" text NULL,
    "ServiceCode" text NULL,
    "ServiceUrl" text NULL,
    "ServiceClientId" text NULL,
    "TimeOutLength" bigint NOT NULL,
    "GlobalLevelOrganisationAccess" boolean NOT NULL,
    "ActivateOrganisations" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_CcsService" PRIMARY KEY ("Id")
);

CREATE TABLE "ContactDetail" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EffectiveFrom" timestamp without time zone NOT NULL,
    "EffectiveTo" timestamp without time zone NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ContactDetail" PRIMARY KEY ("Id")
);

CREATE TABLE "ContactPointReason" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ContactPointReason" PRIMARY KEY ("Id")
);

CREATE TABLE "EnterpriseType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EnterpriseTypeName" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_EnterpriseType" PRIMARY KEY ("Id")
);

CREATE TABLE "IdentityProvider" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdpUri" text NULL,
    "IdpConnectionName" text NULL,
    "IdpName" text NULL,
    "ExternalIdpFlag" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_IdentityProvider" PRIMARY KEY ("Id")
);

CREATE TABLE "PartyType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartyTypeName" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_PartyType" PRIMARY KEY ("Id")
);

CREATE TABLE "UserSettingType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserSettingName" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserSettingType" PRIMARY KEY ("Id")
);

CREATE TABLE "VirtualAddressType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_VirtualAddressType" PRIMARY KEY ("Id")
);

CREATE TABLE "ServicePermission" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServicePermissionName" text NULL,
    "CcsServiceId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ServicePermission" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServicePermission_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PhysicalAddress" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StreetAddress" text NULL,
    "Locality" text NULL,
    "Region" text NULL,
    "PostalCode" text NULL,
    "CountryCode" text NULL,
    "Uprn" text NULL,
    "ContactDetailId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_PhysicalAddress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PhysicalAddress_ContactDetail_ContactDetailId" FOREIGN KEY ("ContactDetailId") REFERENCES "ContactDetail" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Party" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartyTypeId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_Party" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Party_PartyType_PartyTypeId" FOREIGN KEY ("PartyTypeId") REFERENCES "PartyType" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VirtualAddress" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VirtualAddressValue" text NULL,
    "VirtualAddressTypeId" integer NOT NULL,
    "ContactDetailId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_VirtualAddress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VirtualAddress_ContactDetail_ContactDetailId" FOREIGN KEY ("ContactDetailId") REFERENCES "ContactDetail" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VirtualAddress_VirtualAddressType_VirtualAddressTypeId" FOREIGN KEY ("VirtualAddressTypeId") REFERENCES "VirtualAddressType" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ServiceRolePermission" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ServicePermissionId" integer NOT NULL,
    "CcsAccessRoleId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ServiceRolePermission" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ServiceRolePermission_CcsAccessRole_CcsAccessRoleId" FOREIGN KEY ("CcsAccessRoleId") REFERENCES "CcsAccessRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ServiceRolePermission_ServicePermission_ServicePermissionId" FOREIGN KEY ("ServicePermissionId") REFERENCES "ServicePermission" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ContactPoint" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartyId" integer NOT NULL,
    "PartyTypeId" integer NOT NULL,
    "ContactDetailId" integer NOT NULL,
    "ContactPointReasonId" integer NOT NULL,
    "SiteName" text NULL,
    "IsSite" boolean NOT NULL,
    "OriginalContactPointId" integer NOT NULL,
    "AssignedContactType" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ContactPoint" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContactPoint_ContactDetail_ContactDetailId" FOREIGN KEY ("ContactDetailId") REFERENCES "ContactDetail" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContactPoint_ContactPointReason_ContactPointReasonId" FOREIGN KEY ("ContactPointReasonId") REFERENCES "ContactPointReason" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContactPoint_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContactPoint_PartyType_PartyTypeId" FOREIGN KEY ("PartyTypeId") REFERENCES "PartyType" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Organisation" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CiiOrganisationId" text NULL,
    "LegalName" text NULL,
    "OrganisationUri" text NULL,
    "RightToBuy" boolean NULL,
    "BusinessType" text NULL,
    "SupplierBuyerType" integer NULL,
    "PartyId" integer NOT NULL,
    "CcsServiceId" integer NULL,
    "IsActivated" boolean NOT NULL,
    "IsSme" boolean NOT NULL,
    "IsVcse" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_Organisation" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Organisation_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Organisation_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("Id") ON DELETE CASCADE
);

CREATE TABLE "User" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NULL,
    "JobTitle" text NULL,
    "UserTitle" integer NOT NULL,
    "PartyId" integer NOT NULL,
    "MfaEnabled" boolean NOT NULL,
    "AccountVerified" boolean NOT NULL,
    "CcsServiceId" integer NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_User_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_User_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SiteContact" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContactPointId" integer NOT NULL,
    "ContactId" integer NOT NULL,
    "OriginalContactId" integer NOT NULL,
    "AssignedContactType" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_SiteContact" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SiteContact_ContactPoint_ContactPointId" FOREIGN KEY ("ContactPointId") REFERENCES "ContactPoint" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganisationAccessRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "OrganisationAccessRoleName" text NULL,
    "OrganisationAccessRoleDescription" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationAccessRole" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationAccessRole_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganisationEligibleIdentityProvider" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "IdentityProviderId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationEligibleIdentityProvider" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationEligibleIdentityProvider_IdentityProvider_Ident~" FOREIGN KEY ("IdentityProviderId") REFERENCES "IdentityProvider" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationEligibleIdentityProvider_Organisation_Organisat~" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganisationEligibleRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "CcsAccessRoleId" integer NOT NULL,
    "MfaEnabled" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationEligibleRole" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationEligibleRole_CcsAccessRole_CcsAccessRoleId" FOREIGN KEY ("CcsAccessRoleId") REFERENCES "CcsAccessRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationEligibleRole_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganisationEnterpriseType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "EnterpriseTypeId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationEnterpriseType" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationEnterpriseType_EnterpriseType_EnterpriseTypeId" FOREIGN KEY ("EnterpriseTypeId") REFERENCES "EnterpriseType" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationEnterpriseType_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganisationUserGroup" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "UserGroupNameKey" text NULL,
    "UserGroupName" text NULL,
    "MfaEnabled" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationUserGroup" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationUserGroup_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Person" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "PartyId" integer NOT NULL,
    "Title" integer NOT NULL,
    "FirstName" text NULL,
    "LastName" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_Person" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Person_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Person_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ProcurementGroup" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ProcurementGroup" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProcurementGroup_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TradingOrganisation" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "TradingName" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_TradingOrganisation" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TradingOrganisation_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IdamUserLogin" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "IdentityProviderId" integer NOT NULL,
    "Location" text NULL,
    "DeviceType" integer NOT NULL,
    "ClientDevice" text NULL,
    "CcsLoginDateTime" timestamp without time zone NOT NULL,
    "CcsLogoutDateTime" timestamp without time zone NOT NULL,
    "LoginSuccessful" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_IdamUserLogin" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IdamUserLogin_IdentityProvider_IdentityProviderId" FOREIGN KEY ("IdentityProviderId") REFERENCES "IdentityProvider" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IdamUserLogin_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserSetting" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "UserSettingTypeId" integer NOT NULL,
    "UserSettingValue" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserSetting" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserSetting_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSetting_UserSettingType_UserSettingTypeId" FOREIGN KEY ("UserSettingTypeId") REFERENCES "UserSettingType" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserIdentityProvider" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationEligibleIdentityProviderId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserIdentityProvider" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserIdentityProvider_OrganisationEligibleIdentityProvider_O~" FOREIGN KEY ("OrganisationEligibleIdentityProviderId") REFERENCES "OrganisationEligibleIdentityProvider" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserIdentityProvider_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ExternalServiceRoleMapping" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CcsServiceId" integer NOT NULL,
    "OrganisationEligibleRoleId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_ExternalServiceRoleMapping" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExternalServiceRoleMapping_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExternalServiceRoleMapping_OrganisationEligibleRole_Organis~" FOREIGN KEY ("OrganisationEligibleRoleId") REFERENCES "OrganisationEligibleRole" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserAccessRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "OrganisationEligibleRoleId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserAccessRole" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserAccessRole_OrganisationEligibleRole_OrganisationEligibl~" FOREIGN KEY ("OrganisationEligibleRoleId") REFERENCES "OrganisationEligibleRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserAccessRole_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrganisationGroupEligibleRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationUserGroupId" integer NOT NULL,
    "OrganisationEligibleRoleId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationGroupEligibleRole" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationGroupEligibleRole_OrganisationEligibleRole_Orga~" FOREIGN KEY ("OrganisationEligibleRoleId") REFERENCES "OrganisationEligibleRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationGroupEligibleRole_OrganisationUserGroup_Organis~" FOREIGN KEY ("OrganisationUserGroupId") REFERENCES "OrganisationUserGroup" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserGroupMembership" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationUserGroupId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "MembershipStartDate" timestamp without time zone NOT NULL,
    "MembershipEndDate" timestamp without time zone NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserGroupMembership" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserGroupMembership_OrganisationUserGroup_OrganisationUserG~" FOREIGN KEY ("OrganisationUserGroupId") REFERENCES "OrganisationUserGroup" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserGroupMembership_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CcsServiceLogin" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CcsServiceId" integer NOT NULL,
    "IdamUserLoginId" integer NOT NULL,
    "TimedOut" boolean NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_CcsServiceLogin" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CcsServiceLogin_CcsService_CcsServiceId" FOREIGN KEY ("CcsServiceId") REFERENCES "CcsService" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CcsServiceLogin_IdamUserLogin_IdamUserLoginId" FOREIGN KEY ("IdamUserLoginId") REFERENCES "IdamUserLogin" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IdamUserLoginRole" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CcsAccessRoleId" integer NOT NULL,
    "IdamUserLoginId" integer NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_IdamUserLoginRole" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IdamUserLoginRole_CcsAccessRole_CcsAccessRoleId" FOREIGN KEY ("CcsAccessRoleId") REFERENCES "CcsAccessRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IdamUserLoginRole_IdamUserLogin_IdamUserLoginId" FOREIGN KEY ("IdamUserLoginId") REFERENCES "IdamUserLogin" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_IdamUserLoginRole_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_BulkUploadDetail_FileKeyId" ON "BulkUploadDetail" ("FileKeyId");

CREATE INDEX "IX_CcsServiceLogin_CcsServiceId" ON "CcsServiceLogin" ("CcsServiceId");

CREATE INDEX "IX_CcsServiceLogin_IdamUserLoginId" ON "CcsServiceLogin" ("IdamUserLoginId");

CREATE INDEX "IX_ContactPoint_ContactDetailId" ON "ContactPoint" ("ContactDetailId");

CREATE INDEX "IX_ContactPoint_ContactPointReasonId" ON "ContactPoint" ("ContactPointReasonId");

CREATE INDEX "IX_ContactPoint_PartyId" ON "ContactPoint" ("PartyId");

CREATE INDEX "IX_ContactPoint_PartyTypeId" ON "ContactPoint" ("PartyTypeId");

CREATE INDEX "IX_ExternalServiceRoleMapping_CcsServiceId" ON "ExternalServiceRoleMapping" ("CcsServiceId");

CREATE INDEX "IX_ExternalServiceRoleMapping_OrganisationEligibleRoleId" ON "ExternalServiceRoleMapping" ("OrganisationEligibleRoleId");

CREATE INDEX "IX_IdamUserLogin_IdentityProviderId" ON "IdamUserLogin" ("IdentityProviderId");

CREATE INDEX "IX_IdamUserLogin_UserId" ON "IdamUserLogin" ("UserId");

CREATE INDEX "IX_IdamUserLoginRole_CcsAccessRoleId" ON "IdamUserLoginRole" ("CcsAccessRoleId");

CREATE INDEX "IX_IdamUserLoginRole_IdamUserLoginId" ON "IdamUserLoginRole" ("IdamUserLoginId");

CREATE INDEX "IX_IdamUserLoginRole_UserId" ON "IdamUserLoginRole" ("UserId");

CREATE INDEX "IX_Organisation_CcsServiceId" ON "Organisation" ("CcsServiceId");

CREATE INDEX "IX_Organisation_CiiOrganisationId" ON "Organisation" ("CiiOrganisationId");

CREATE UNIQUE INDEX "IX_Organisation_PartyId" ON "Organisation" ("PartyId");

CREATE INDEX "IX_OrganisationAccessRole_OrganisationId" ON "OrganisationAccessRole" ("OrganisationId");

CREATE INDEX "IX_OrganisationEligibleIdentityProvider_IdentityProviderId" ON "OrganisationEligibleIdentityProvider" ("IdentityProviderId");

CREATE INDEX "IX_OrganisationEligibleIdentityProvider_OrganisationId" ON "OrganisationEligibleIdentityProvider" ("OrganisationId");

CREATE INDEX "IX_OrganisationEligibleRole_CcsAccessRoleId" ON "OrganisationEligibleRole" ("CcsAccessRoleId");

CREATE INDEX "IX_OrganisationEligibleRole_OrganisationId" ON "OrganisationEligibleRole" ("OrganisationId");

CREATE INDEX "IX_OrganisationEnterpriseType_EnterpriseTypeId" ON "OrganisationEnterpriseType" ("EnterpriseTypeId");

CREATE INDEX "IX_OrganisationEnterpriseType_OrganisationId" ON "OrganisationEnterpriseType" ("OrganisationId");

CREATE INDEX "IX_OrganisationGroupEligibleRole_OrganisationEligibleRoleId" ON "OrganisationGroupEligibleRole" ("OrganisationEligibleRoleId");

CREATE INDEX "IX_OrganisationGroupEligibleRole_OrganisationUserGroupId" ON "OrganisationGroupEligibleRole" ("OrganisationUserGroupId");

CREATE INDEX "IX_OrganisationUserGroup_OrganisationId" ON "OrganisationUserGroup" ("OrganisationId");

CREATE INDEX "IX_Party_PartyTypeId" ON "Party" ("PartyTypeId");

CREATE INDEX "IX_Person_OrganisationId" ON "Person" ("OrganisationId");

CREATE UNIQUE INDEX "IX_Person_PartyId" ON "Person" ("PartyId");

CREATE UNIQUE INDEX "IX_PhysicalAddress_ContactDetailId" ON "PhysicalAddress" ("ContactDetailId");

CREATE INDEX "IX_ProcurementGroup_OrganisationId" ON "ProcurementGroup" ("OrganisationId");

CREATE INDEX "IX_ServicePermission_CcsServiceId" ON "ServicePermission" ("CcsServiceId");

CREATE INDEX "IX_ServiceRolePermission_CcsAccessRoleId" ON "ServiceRolePermission" ("CcsAccessRoleId");

CREATE INDEX "IX_ServiceRolePermission_ServicePermissionId" ON "ServiceRolePermission" ("ServicePermissionId");

CREATE INDEX "IX_SiteContact_ContactPointId" ON "SiteContact" ("ContactPointId");

CREATE INDEX "IX_TradingOrganisation_OrganisationId" ON "TradingOrganisation" ("OrganisationId");

CREATE INDEX "IX_User_CcsServiceId" ON "User" ("CcsServiceId");

CREATE UNIQUE INDEX "IX_User_PartyId" ON "User" ("PartyId");

CREATE INDEX "IX_User_UserName" ON "User" ("UserName");

CREATE INDEX "IX_UserAccessRole_OrganisationEligibleRoleId" ON "UserAccessRole" ("OrganisationEligibleRoleId");

CREATE INDEX "IX_UserAccessRole_UserId" ON "UserAccessRole" ("UserId");

CREATE INDEX "IX_UserGroupMembership_OrganisationUserGroupId" ON "UserGroupMembership" ("OrganisationUserGroupId");

CREATE INDEX "IX_UserGroupMembership_UserId" ON "UserGroupMembership" ("UserId");

CREATE INDEX "IX_UserIdentityProvider_OrganisationEligibleIdentityProviderId" ON "UserIdentityProvider" ("OrganisationEligibleIdentityProviderId");

CREATE INDEX "IX_UserIdentityProvider_UserId" ON "UserIdentityProvider" ("UserId");

CREATE INDEX "IX_UserSetting_UserId" ON "UserSetting" ("UserId");

CREATE INDEX "IX_UserSetting_UserSettingTypeId" ON "UserSetting" ("UserSettingTypeId");

CREATE INDEX "IX_VirtualAddress_ContactDetailId" ON "VirtualAddress" ("ContactDetailId");

CREATE INDEX "IX_VirtualAddress_VirtualAddressTypeId" ON "VirtualAddress" ("VirtualAddressTypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211224054428_InitialMigration', '5.0.10');

COMMIT;

