START TRANSACTION;

ALTER TABLE "CcsAccessRole" ADD "ApprovalRequired" integer NOT NULL DEFAULT 0;

CREATE TABLE "RoleApprovalConfiguration" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CcsAccessRoleId" integer NOT NULL,
    "LinkExpiryDurationInMinute" integer NOT NULL,
    "NotificationEmails" text NULL,
    "EmailTemplate" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_RoleApprovalConfiguration" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleApprovalConfiguration_CcsAccessRole_CcsAccessRoleId" FOREIGN KEY ("CcsAccessRoleId") REFERENCES "CcsAccessRole" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserAccessRolePending" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "OrganisationEligibleRoleId" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_UserAccessRolePending" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserAccessRolePending_OrganisationEligibleRole_Organisation~" FOREIGN KEY ("OrganisationEligibleRoleId") REFERENCES "OrganisationEligibleRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserAccessRolePending_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RoleApprovalConfiguration_CcsAccessRoleId" ON "RoleApprovalConfiguration" ("CcsAccessRoleId");

CREATE INDEX "IX_UserAccessRolePending_OrganisationEligibleRoleId" ON "UserAccessRolePending" ("OrganisationEligibleRoleId");

CREATE INDEX "IX_UserAccessRolePending_UserId" ON "UserAccessRolePending" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221227080442_Role_Approval', '5.0.10');

COMMIT;


START TRANSACTION;

ALTER TABLE "RoleApprovalConfiguration" DROP COLUMN "EmailTemplate";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230105120311_Remove_RoleApprovalConfiguration_EmailTemplate', '5.0.10');

COMMIT;

