START TRANSACTION;

ALTER TABLE "User" ADD "DelegationLinkExpiryOnUtc" timestamp without time zone NULL;

CREATE TABLE "DelegationAuditEvent" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GroupId" uuid NOT NULL,
    "UserId" integer NOT NULL,
    "PreviousDelegationStartDate" timestamp without time zone NULL,
    "PreviousDelegationEndDate" timestamp without time zone NULL,
    "NewDelegationStartDate" timestamp without time zone NULL,
    "NewDelegationEndDate" timestamp without time zone NULL,
    "Roles" text NULL,
    "EventType" text NULL,
    "ActionedOnUtc" timestamp without time zone NOT NULL,
    "ActionedBy" text NULL,
    "ActionedByUserName" text NULL,
    "ActionedByFirstName" text NULL,
    "ActionedByLastName" text NULL,
    CONSTRAINT "PK_DelegationAuditEvent" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DelegationAuditEvent_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_DelegationAuditEvent_UserId" ON "DelegationAuditEvent" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230515053104_Add_Delegation_Audit_Event', '5.0.10');

COMMIT;

