START TRANSACTION;

CREATE TABLE "DataMigrationDetail" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileKey" text NULL,
    "FileKeyId" text NULL,
    "DocUploadId" text NULL,
    "DataMigrationStatus" integer NOT NULL,
    "ValidationErrorDetails" text NULL,
    "MigrationStartedOnUtc" timestamp without time zone NOT NULL,
    "MigrationEndedOnUtc" timestamp without time zone NOT NULL,
    "MigrationStringContent" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_DataMigrationDetail" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230420123153_Add_New_Table_DataMigrationDetail', '5.0.10');

COMMIT;

