START TRANSACTION;

CREATE TABLE "CountryDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" text NULL,
    "Name" text NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_CountryDetails" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220119113124_CountryDetails', '5.0.10');

COMMIT;

-- Insert Script for CountryDetails