START TRANSACTION;

CREATE TABLE "OrganisationAuditEvent" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "SchemeIdentifier" text NULL,
    "FirstName" text NULL,
    "LastName" text NULL,
    "GroupId" uuid NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Actioned" text NULL,
    "ActionedBy" text NULL,
    "Event" text NULL,
    "Roles" text NULL,
    CONSTRAINT "PK_OrganisationAuditEvent" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationAuditEvent_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrganisationAuditEvent_OrganisationId" ON "OrganisationAuditEvent" ("OrganisationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221021043140_Add_Table_OrganisationAuditEvent', '5.0.10');

COMMIT;

