START TRANSACTION;

CREATE TABLE "OrganisationAudit" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Status" integer NOT NULL,
    "OrganisationId" integer NOT NULL,
    "SchemeIdentifier" text NULL,
    "Actioned" text NULL,
    "ActionedBy" text NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_OrganisationAudit" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationAudit_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrganisationAudit_OrganisationId" ON "OrganisationAudit" ("OrganisationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221027092836_Add_Table_OrganisationAudit', '5.0.10');

COMMIT;

