START TRANSACTION;

CREATE TABLE "OrganisationEligibleRolePending" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrganisationId" integer NOT NULL,
    "CcsAccessRoleId" integer NOT NULL,
    "CreatedUserId" integer NOT NULL,
    "LastUpdatedUserId" integer NOT NULL,
    "CreatedOnUtc" timestamp without time zone NOT NULL,
    "LastUpdatedOnUtc" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ConcurrencyKey" bytea NULL,
    CONSTRAINT "PK_OrganisationEligibleRolePending" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrganisationEligibleRolePending_CcsAccessRole_CcsAccessRole~" FOREIGN KEY ("CcsAccessRoleId") REFERENCES "CcsAccessRole" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrganisationEligibleRolePending_Organisation_OrganisationId" FOREIGN KEY ("OrganisationId") REFERENCES "Organisation" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrganisationEligibleRolePending_CcsAccessRoleId" ON "OrganisationEligibleRolePending" ("CcsAccessRoleId");

CREATE INDEX "IX_OrganisationEligibleRolePending_OrganisationId" ON "OrganisationEligibleRolePending" ("OrganisationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221202085551_Add_Table_OrganisationEligibleRolePending', '5.0.10');

COMMIT;

