<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.S3" Version="4.0.22.2" />
		<PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.7.14" />
		<PackageReference Include="AWSSDK.SQS" Version="4.0.2.28" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />

		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.18.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
		<PackageReference Include="System.Text.Encodings.Web" Version="10.0.7" />
		<PackageReference Include="System.Text.Json" Version="10.0.7" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
    <ProjectReference Include="..\CcsSso.Shared.Cache\CcsSso.Shared.Cache.csproj" />
  </ItemGroup>

</Project>
