-- Insert Initial CountryDetails
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AD','Andorra', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AE','United Arab Emirates', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AF','Afghanistan', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AG','Antigua and Barbuda', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AI','Anguilla', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AL','Albania', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AM','Armenia', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AO','Angola', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AR','Argentina', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AT','Austria', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AU','Australia', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('AZ','Azerbaijan', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BA','Bosnia and Herzegovina', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BB','Barbados', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BD','Bangladesh', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BE','Belgium', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BF','Burkina Faso', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BG','Bulgaria', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BH','Bahrain', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BI','Burundi', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BJ','Benin', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BM','Bermuda', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BN','Brunei', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BO','Bolivia', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BR','Brazil', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BS','The Bahamas', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BT','Bhutan', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BW','Botswana', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BY','Belarus', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('BZ','Belize', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CA','Canada', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CD','Congo (Democratic Republic)', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CF','Central African Republic', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CG','Congo', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CH','Switzerland', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CI','Ivory Coast', 0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CL','Chile',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CM','Cameroon',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CN','China',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CO','Colombia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CR','Costa Rica',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CU','Cuba',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CV','Cape Verde',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CY','Cyprus',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('CZ','Czechia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('DE','Germany',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('DJ','Djibouti',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('DK','Denmark',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('DM','Dominica',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('DO','Dominican Republic',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('DZ','Algeria',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('EC','Ecuador',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('EE','Estonia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('EG','Egypt',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ER','Eritrea',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ES','Spain',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ET','Ethiopia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('FI','Finland',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('FJ','Fiji',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('FK','Falkland Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('FM','Micronesia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('FR','France',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GA','Gabon',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GB','United Kingdom',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GB-ENG','England',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GB-NIR','Northern Ireland',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GB-SCT','Scotland',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GB-WLS','Wales',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GD','Grenada',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GE','Georgia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GH','Ghana',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GI','Gibraltar',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GM','The Gambia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GN','Guinea',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GQ','Equatorial Guinea',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GR','Greece',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GS','South Georgia and South Sandwich Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GT','Guatemala',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GW','Guinea-Bissau',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('GY','Guyana',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('HN','Honduras',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('HR','Croatia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('HT','Haiti',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('HU','Hungary',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ID','Indonesia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IE','Ireland',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IL','Israel',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IN','India',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IO','British Indian Ocean Territory',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IQ','Iraq',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IR','Iran',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IS','Iceland',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('IT','Italy',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('JM','Jamaica',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('JO','Jordan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('JP','Japan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KE','Kenya',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KG','Kyrgyzstan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KH','Cambodia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KI','Kiribati',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KM','Comoros',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KN','St Kitts and Nevis',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KP','North Korea',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KR','South Korea',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KW','Kuwait',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KY','Cayman Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('KZ','Kazakhstan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LA','Laos',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LB','Lebanon',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LC','St Lucia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LI','Liechtenstein',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LK','Sri Lanka',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LR','Liberia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LS','Lesotho',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LT','Lithuania',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LU','Luxembourg',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LV','Latvia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('LY','Libya',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MA','Morocco',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MC','Monaco',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MD','Moldova',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ME','Montenegro',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MG','Madagascar',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MH','Marshall Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MK','North Macedonia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ML','Mali',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MM','Myanmar (Burma)',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MN','Mongolia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MR','Mauritania',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MS','Montserrat',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MT','Malta',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MU','Mauritius',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MV','Maldives',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MW','Malawi',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MX','Mexico',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MY','Malaysia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('MZ','Mozambique',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NA','Namibia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NE','Niger',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NG','Nigeria',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NI','Nicaragua',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NL','Netherlands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NO','Norway',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NP','Nepal',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NR','Nauru',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('NZ','New Zealand',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('OM','Oman',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PA','Panama',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PE','Peru',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PG','Papua New Guinea',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PH','Philippines',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PK','Pakistan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PL','Poland',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PN','Pitcairn, Henderson, Ducie and Oeno Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PT','Portugal',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PW','Palau',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('PY','Paraguay',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('QA','Qatar',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('RO','Romania',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('RS','Serbia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('RU','Russia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('RW','Rwanda',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SA','Saudi Arabia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SB','Solomon Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SC','Seychelles',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SD','Sudan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SE','Sweden',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SG','Singapore',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SH','St Helena, Ascension and Tristan da Cunha',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SI','Slovenia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SK','Slovakia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SL','Sierra Leone',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SM','San Marino',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SN','Senegal',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SO','Somalia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SR','Suriname',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SS','South Sudan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ST','Sao Tome and Principe',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SV','El Salvador',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SY','Syria',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('SZ','Eswatini',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TC','Turks and Caicos Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TD','Chad',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TG','Togo',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TH','Thailand',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TJ','Tajikistan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TL','East Timor',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TM','Turkmenistan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TN','Tunisia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TO','Tonga',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TR','Turkey',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TT','Trinidad and Tobago',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TV','Tuvalu',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('TZ','Tanzania',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('UA','Ukraine',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('UG','Uganda',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('US','United States',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('UY','Uruguay',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('UZ','Uzbekistan',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('VA','Vatican City',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('VC','St Vincent',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('VE','Venezuela',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('VG','British Virgin Islands',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('VN','Vietnam',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('VU','Vanuatu',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('WS','Samoa',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('XK','Kosovo',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('YE','Yemen',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ZA','South Africa',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ZM','Zambia',0, 0, now(), now(), false);
INSERT INTO public."CountryDetails"("Code", "Name", "CreatedUserId", "LastUpdatedUserId", "CreatedOnUtc", "LastUpdatedOnUtc", "IsDeleted") VALUES ('ZW','Zimbabwe',0, 0, now(), now(), false);
