name: .NET

on:
  push:
    branches: [ sandbox-cicd ]
  pull_request:
    branches: [ sandbox-cicd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./api/CcsSso.sln
    - name: Build
      run: dotnet build --configuration Release ./api/CcsSso.sln
    - name: Get jFrog artifactory ready
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
    - run: |
        jfrog rt ping /
        jfrog rt upload api/CcsSso.Core.ExternalApi/bin/Release/net5.0/ ccs-nuget --flat=false --build-name=api-wrapper --build-number=release-commit_id100 / 
        jfrog rt build-publish api-wrapper release-commit_id100 /
    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

 